#!/bin/bash
# Start learning test with one robot with supervisor.

python start.py --output-directory output --restore-directory restore --population-size 50 --num-children 45 --tournament-size 40 --eval-time 20 --speciation-threshold 0.01 --test-bot "../testBots/snake" --max-generations 10000

