#!/bin/bash
# Start learning test with one robot with supervisor.

python start.py --output-directory output --restore-directory restore --population-size 5 --num-children 4 --tournament-size 4 --evaluation-time 30 --warmup-time 3 --speciation-threshold 0.03 --test-bot "../testBots/spider" --max-generations 100 --repeat-evaluations 1

