#!/bin/bash
# Start learning test with one robot with supervisor.

python start.py --output-directory output --restore-directory restore --population-size 50 --num-children 45 --tournament-size 40 --evaluation-time 30 --warmup-time 3 --speciation-threshold 0.00 --test-bot "../testBots/fish" --max-generations 1000 --repeat-evaluations 1

