#!/bin/bash
# Runs gazebo with the correct plugin path
WORLD=gait-learning.world
CMD=gazebo
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
echo "DIR="$DIR


# launch gazebo:
GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:`pwd`/../../build GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:`pwd`/../../tools/models $CMD -u $WORLD 2> >(grep -v -e '^$' -e 'LCP internal error') &
GZ_PID=$!

echo $GAZEBO_PLUGIN_PATH
echo $GAZEBO_MODEL_PATH


../../../revolve/tools/analyzer/run-analyzer &
ANALYZER_PID=$!

sleep 2

ACTUAL_ANALYZER_PID=`ps -ef | awk '$3 == '${ANALYZER_PID}' { print $2 } '`

sleep 3

python $DIR/swap_test.py &
PY_PID=$!

echo 'PY_PID='$PY_PID

wait $GZ_PID
kill ${ACTUAL_ANALYZER_PID}
kill $(jobs -rp)
wait $(jobs -rp) 2>/dev/null
echo "Done."
